project:
  type: website
  render:
    - "*.qmd"
    - "!rcodes/qmd/"
website:
  site-url: ""
  sidebar:
    style: docked
    title: "STA 6856"
    logo: assets/logo.png
    tools:
      - icon: github
        href: https://github.com/UWFTeaching/timeseries
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: staff.qmd
        text: Instructor
      - href: project.qmd
        text: Slides
      - href: data.qmd
        text: R code


format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



