---
title: "STA 6856 - Time Series Analysis"
subtitle: "UWF - Mathematics and Statistics"
# listing:
#   - id: schedule
#     template: assets/schedule.ejs
#     contents: schedule.yml
#   - id: buttons
#     template: assets/buttons.ejs
#     contents: buttons.yml
---

```{=html}
<!--::: {#buttons}
:::



::: {.callout-note title="Welcome to Week 1 of Stat 999"}
:::

::: {.callout-note title="Welcome to Week 2"}
Things are picking up now.
:::-->
```
Time series data is data that is focused on time and can be utilized for predicting future values or analyzing data. This course will give students an essential comprehension of the nature and basic processes used to analyze such data. The course will cover the theory and practice of time series analysis, with a focus on modeling and forecasting. Successfully completing assignments will require a combination of computing and statistics/mathematics. R will be utilized for computer-oriented analysis.

## Schedule


|| **Week** | **Day** | **Topic(s)** | **Readings/Tasks** |
|:-:|:---:|:--------------------|:--:|
| 1    | M     | Introduction to Time Series | Slides 1-16|
|      | W     | Introduction to R/RStudio/Quarto for Time Series | |
| 2    | M     | Practice Assignment 1 Group **no meeting** | |
|      | W     | Introduction to R/RStudio/Quarto for Time Series | |
| 3    | M     | **Labor Day 9/2 Holiday**
|      | W     | Zero-Mean Simple Models + Covariance | Slides 17-27|
|  4   | M     | Stationary + ACF + MA(1) | Slides 28-38  | 
|      | W     | TS decomposition + Trend/Seasonality Estimation/Elimination | Slides 39-46|
|  5   | M     | TS decomposition + Trend/Seasonality Estimation/Elimination|  | 
|      | W     | Differencing Operator + Examples with R | Slides 47-52| 
|  6   | M     | TS Decomposition - Practice Assignment 2 Group - **no meeting**| |
|      | W     | Stationary processes + ARMA(p,q)  |Slides 75-91 |
|  7   | M     | Estimation Mean and ACF + ARMA models |  | 
|      | W     | ARMA modeling | |
|  8   | M     | ARMA Practice Assignment 3 Group - **no meeting** | |
|      | W     | Review - | |
|   9  | M     | Mid-term Exam Project **no meeting** ||
|      | W     | ARIMA models | Slides 94-99  |
|   10 | M     | ARIMA models in R |  |
|      | W     | SARIMA models | |
|   11 | M     | SARIMA models - R Examples| |
|      | W     | SARIMA Practice Assignment 4 Group - **no meeting** | |
|   12 | M     | Forecasting| |
|      | W     | Forecasting Practice Assignment 5 Group - **no meeting**| |
|   13 | M     | **Veteran Day 11/11 Holiday**| |
|      | W     |  Regression with ARMA Errors | |
|  14  | M     |  Regression TS Practice Assignment 6 Group - **no meeting** | |
|      | W     | Additional topics   | |
|  15  | M     | Review  | |
|      | W     | **Thanksgiving** | |
|   16 | M     | **Final Exam on Monday** - Final Week  | |
