project:
  type: website

website:
  navbar:
    title: false
    logo: panda-logo.png
    left:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: calendar.qmd
        text: Calendar


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

